---
flighdeck_motd_name: "Tractorbeam 2.0.0"

flightdeck_groups:
  - name: "backup"

flightdeck_users:
  - name: "backup"
    group: "backup"
    groups:
      - "cron"
    home: "/home/backup"

flightdeck_root_prompt: '\u@tractorbeam:\w# '
flightdeck_user_prompt: '\u@tractorbeam:\w$ '
