---
- name: Generate the backup timestamp.
  set_fact:
    _backup_timestamp: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"
- name: Create a temp directory to store files needed by the run
  tempfile:
    state: directory
    prefix: "tractorbeam_db-run-{{ _backup_timestamp }}"
  register: _run_temp_dir
  notify:
    - delete temp items
- name: Work with backups
  include_tasks: "backup.yml"
  vars:
    _retain_count: "{{ tractorbeam_db_expiries[tractorbeam_db_scope] }}"
  loop: "{{ tractorbeam.databases }}"
  loop_control:
    loop_var: _bucket
  no_log: "{{ tractorbeam_db_nolog | default(true) }}"
